schema_version: 1

context:
  version: "4.4.0"

package:
  name: fhirclient
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fhirclient/fhirclient-${{ version }}.tar.gz
  sha256: 922d6110f941741a67fdb8dc3afdeba21b8d1f30beafde7d2fbe523cf9192188

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - flit-core >=3.4,<4
    - pip
    - requests >=2.4
  run:
    - python >=${{ python_min }}
    - requests >=2.4

tests:
  - python:
      imports:
        - fhirclient
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: A flexible client for FHIR servers supporting the SMART on FHIR protocol
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/smart-on-fhir/client-py

extra:
  recipe-maintainers:
    - danielnachun
